language: python
python:
  - "3.7"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov pytest-cov
  
install:
  - pip install .

script:
  - metexpy --help
  - pytest --cov=metexpy tests/

after_script:
  - codecov
